### ISSUE TITLE
update instructions

### ISSUE THREAD

**Issue by victorbstan** [drewjw81/meteor-googlemaps#10]
Hello,

So AFAIK `meteorite` is not required to install packages for meteor anymore.

What are the correct install instructions to replace this then?

```
How to install:

make sure you have meteorite installed
$ npm install -g meteorite
inside your project, run:
$ mrt add googlemaps
```

**Comment by drewjw81** [comment]
Just got control of this package again.  Will update shortly.

**Comment by dandv** [comment]
How is this package different from @dburles's? Maybe join efforts with his?

https://atmospherejs.com/dburles/google-maps

Background: I'm leading an effort of [clearing up Atmosphere of outdated packages](https://github.com/percolatestudio/atmosphere/issues/297). If you'd like to hide this package from Atmosphere searches but still keep it installable by apps that use it, all you need to do is run

    meteor admin set-unmigrated mrt:googlemaps

**Comment by drewjw81** [comment]
Done. @dburles's actively developed and much further ahead of this one I recommend people use that.
