### ISSUE TITLE
Content Security Policy issue

### ISSUE THREAD

**Issue by filipeportes** [drewjw81/meteor-googlemaps#11]
browser showing the following message:

Content Security Policy: The page's settings blocked the loading of a resource at http://maps.googleapis.com/maps/api/js?sensor=true&key=MY-GOOGLEMAPS-API-KEY&language=de&callback=GoogleMaps.callback ("script-src http://localhost:3000 'unsafe-inline'").

**Comment by ARastogi19** [comment]
Were you able to find a workaround for this issue?

**Comment by drewjw81** [comment]
You should probably use https://github.com/dburles/meteor-google-maps since it's supported. Thanks for using this one though.
