### ISSUE TITLE
Is it ok to call `GoogleMaps.init` multiple times?

### ISSUE THREAD

**Issue by boilingApps** [drewjw81/meteor-googlemaps#5]
Hi drewjw81,

I have been working with your package for a while, and my experience had been smooth, until recently.

### Problem

Right now I need to initialize two separate Autocomplete on two input tags on different pages.

On page 1:
`var autocomplete1 = new google.maps.places.Autocomplete(input1);`
On page 2:
`var autocomplete2 = new google.maps.places.Autocomplete(input2);`

Adding one autocomplete is simple and smooth. However, as soon as I add the second autocomplete on another page or go to the other page where I add the second autocomplete, the code gives me the following errors:

`Exception from Tracker afterFlush function: google is not defined
ReferenceError: google is not defined`

### My solution

I have solved the problem by using the following method twice in the app:

```
getAutocomplete = function(input) {
  $(document).ready(function() {
    GoogleMaps.init({
      'v': '3.9',
      'libraries': 'places'
    }, function() {
      return autocomplete = new google.maps.places.Autocomplete(input);
    });
  });
}
```

### Questions:

I didn't read thru your `init` method closely, just yet. But I'd like to hear your advice on this approach first.

Do you think it is ok to call `GoogleMaps.init` multiple times in the app? Or is there another approach?

Thanks in advance!

**Comment by drewjw81** [comment]
Sorry for the delay. To answer your question, yes, you can safely call init multiple times.  Have you had any issues doing so?

**Comment by pdiniz13** [comment]
I was having the same issue and boilingApps solution also worked for me.
