### ISSUE TITLE
Exposing API Key in Client

### ISSUE THREAD

**Issue by lukeclifton** [drewjw81/meteor-googlemaps#6]
Hey. Thanks for this package.

Just a thought, if the init code goes in the client won't this expose the API key? Is there a way to avoid this?

**Comment by drewjw81** [comment]
That's true, but that's the standard practice with google maps JS anyway.

    <script type="text/javascript" 
        src="https://maps.googleapis.com/maps/api/js?key=API_KEY">
    </script>
