### ISSUE TITLE
Add Atmosphere page as GitHub repo url

### ISSUE THREAD

**Issue by dandv** [drewjw81/meteor-googlemaps#7]
Like ![image](https://cloud.githubusercontent.com/assets/33569/3532709/6aac4a7c-07c1-11e4-8261-efe20dc5196e.png)

**Comment by drewjw81** [comment]
Thanks, I'll take care of this as soon as I've re-claimed the package and have a new link

**Comment by dandv** [comment]
@drewjw81: looks like [you got control of the package](https://github.com/drewjw81/meteor-googlemaps/issues/10#issuecomment-70434442)?
