### ISSUE TITLE
Is this package mrt:googlemaps?

### ISSUE THREAD

**Issue by dandv** [drewjw81/meteor-googlemaps#8]
That package, https://atmospherejs.com/mrt/googlemaps, has a lot of downloads. It would be nice to set a proper name in Package.js, set the README etc. For a canonical package.js please see https://github.com/dandv/meteor-jquery-rateit/blob/master/package.js

**Comment by samosfator** [comment]
:+1: There is some misunderstanding at the moment.

**Comment by drewjw81** [comment]
Looks like it.  Working on claiming it and starting to maintain it again now.

**Comment by drewjw81** [comment]
Done, should update in atmosphere soon now that I have reclaimed and published.
