### ISSUE TITLE
Conflicts with dburles:google-maps

### ISSUE THREAD

**Issue by bmx269** [drewjw81/meteor-googlemaps#9]
It seams you both are using the GoogleMaps namespace, do you think you could work together to be more compatible? https://github.com/dburles/meteor-google-maps/

**Comment by dandv** [comment]
Maybe the better question is, how is this project different from @dubrles', and why not join forces?

**Comment by theroadrunnershow** [comment]
+1 to this request.
@bmx269 Would love to be able to use this in conjuction with  https://github.com/dburles/meteor-google-maps/

**Comment by dandv** [comment]
Maybe the better question is, how is this project different from @dburles's, and why not join forces?

**Comment by drewjw81** [comment]
@dandv, @dburles is much better supported than mine I would suggest people use that.
